//! Turns the language's executable documents into named Rust tests.
//!
//! `ref/src/test/nucleoid.spec.js` writes one `it(...)` per behaviour, so a
//! failure names the behaviour that broke. The cases here live in the documents
//! rather than in the test files, so the `it`s are generated from them — which
//! also keeps the promise in `CLAUDE.md` that adding a case to a document adds
//! a test, with nothing else to edit.
//!
//! The authoritative `nucleoid.spec.md` suite is the exception: its generated
//! Rust tests are committed in `tests/spec_cases/mod.rs`, so each use case can be
//! read and run without loading Markdown. `tests/spec.rs` separately checks
//! that the committed copy remains identical to the document.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// How a document holds its cases.
#[derive(Clone, Copy, PartialEq)]
enum Format {
    /// A fenced block of cases split by `---`, each titled by its first comment
    /// line.
    Cases,
    /// Prose with fenced `nuc` blocks in it, each titled by the bold claim
    /// it demonstrates.
    Snippets,
}

/// One generated test file, and the documents whose cases go into it. Each
/// document becomes a module, the way `describe(...)` groups `it`s.
struct Suite {
    output: &'static str,
    format: Format,
    source: Source,
}

/// Where a suite's documents come from.
enum Source {
    /// Named one by one, for the suites that have exactly one document.
    Named(&'static [(&'static str, &'static str)]),
    /// Every `.md` in a directory, in name order. The synth sets are added to
    /// in batches, and a batch should not have to be wired in by hand.
    Directory(&'static str),
}

const SUITES: &[Suite] = &[
    Suite {
        output: "synth.rs",
        format: Format::Cases,
        source: Source::Directory("synth"),
    },
    Suite {
        output: "reference.rs",
        format: Format::Cases,
        source: Source::Named(&[("reference", "tests/reference.md")]),
    },
    Suite {
        output: "readme.rs",
        format: Format::Snippets,
        source: Source::Named(&[("readme", "README.md")]),
    },
    Suite {
        output: "examples.rs",
        format: Format::Snippets,
        source: Source::Named(&[("examples", "docs/examples.md")]),
    },
];

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-env-changed=UPDATE_SPEC_TESTS");

    if env::var_os("UPDATE_SPEC_TESTS").is_some() {
        write_spec_tests();
    }

    let out = env::var("OUT_DIR").expect("cargo sets OUT_DIR for build scripts");

    for suite in SUITES {
        let mut generated = String::new();
        generated.push_str("// @generated by build.rs — do not edit.\n\n");

        let mut total = 0;
        let mut modules = String::new();

        let documents = match suite.source {
            Source::Named(documents) => documents
                .iter()
                .map(|(module, path)| ((*module).to_string(), (*path).to_string()))
                .collect(),
            Source::Directory(directory) => {
                println!("cargo::rerun-if-changed={directory}");
                in_directory(directory)
            }
        };

        if let Source::Directory(_) = suite.source {
            write_document_list(&out, &documents);
        }

        for (index, (module, path)) in documents.iter().enumerate() {
            println!("cargo::rerun-if-changed={path}");

            let document = fs::read_to_string(path)
                .unwrap_or_else(|error| panic!("{path} states what the language does: {error}"));

            let titles = match suite.format {
                Format::Cases => case_titles(&document),
                Format::Snippets => snippet_titles(&document),
            };

            reject_duplicates(path, &titles);

            total += titles.len();
            modules.push_str(&module_for(module, index, &titles));
        }

        writeln!(generated, "pub const GENERATED: usize = {total};\n").unwrap();
        generated.push_str(&modules);

        fs::write(Path::new(&out).join(suite.output), generated)
            .expect("the generated tests must be writable");
    }
}

struct Case {
    title: String,
    source: String,
    expected: Option<String>,
}

/// Materializes `nucleoid.spec.md` as editable, committed Rust tests.
///
/// Run with `UPDATE_SPEC_TESTS=1 cargo build`. The synchronization test in
/// `tests/spec.rs` rejects a stale copy.
fn write_spec_tests() {
    let document = fs::read_to_string("nucleoid.spec.md")
        .expect("nucleoid.spec.md states what the language does");
    let cases = parse_cases(&document);
    let mut generated = String::from(
        "// @generated from nucleoid.spec.md by `UPDATE_SPEC_TESTS=1 cargo build`.\n\
         // The cases are committed so they can be read and run without parsing Markdown.\n\n\
         const CASES: &[SpecCase] = &[\n",
    );
    let mut tests = String::new();
    let mut taken = Vec::new();

    for (index, case) in cases.iter().enumerate() {
        writeln!(generated, "    SpecCase {{").unwrap();
        writeln!(generated, "        title: {:?},", case.title).unwrap();
        writeln!(generated, "        source: {},", raw_literal(&case.source)).unwrap();

        match &case.expected {
            Some(expected) => {
                writeln!(generated, "        expected: Some({expected:?}),").unwrap();
            }
            None => generated.push_str("        expected: None,\n"),
        }

        generated.push_str("    },\n");

        let name = unique(identifier(&case.title), &mut taken);
        writeln!(tests, "/// {}", case.title).unwrap();
        tests.push_str("#[test]\n");
        writeln!(tests, "fn {name}() {{").unwrap();
        writeln!(tests, "    case({index});").unwrap();
        tests.push_str("}\n\n");
    }

    generated.push_str("];\n\n");
    generated.push_str(&tests);

    fs::create_dir_all("tests/spec_cases").expect("tests/spec_cases must be writable");
    fs::write("tests/spec_cases/mod.rs", generated)
        .expect("tests/spec_cases/mod.rs must be writable");
}

fn parse_cases(document: &str) -> Vec<Case> {
    let document = document.replace("\r\n", "\n");
    let body = document
        .split("```")
        .nth(1)
        .expect("cases live in one fenced block");

    body.split("\n---\n")
        .filter(|block| !block.trim().is_empty())
        .map(|block| {
            let title = block
                .lines()
                .map(str::trim)
                .find(|line| line.starts_with('#'))
                .unwrap_or("untitled")
                .trim_start_matches('#')
                .trim()
                .to_string();
            let expected = block.lines().map(str::trim).find_map(|line| {
                line.strip_prefix("# return:")
                    .map(|rest| rest.trim().to_string())
            });
            let source = block
                .lines()
                .filter(|line| !line.trim().starts_with("# return:"))
                .collect::<Vec<_>>()
                .join("\n");

            Case {
                title,
                source,
                expected,
            }
        })
        .collect()
}

fn raw_literal(value: &str) -> String {
    for hashes in 1.. {
        let marker = format!("\"{}", "#".repeat(hashes));

        if !value.contains(&marker) {
            let hashes = "#".repeat(hashes);
            return format!("r{hashes}\"{value}\"{hashes}");
        }
    }

    unreachable!("a raw string delimiter is always available")
}

/// Every `.md` in a directory, as `(module, path)` in name order.
///
/// `synth/nucleoid.spec.synth.01.md` becomes the module `synth_01`, so a test
/// path still says which set the case came from.
fn in_directory(directory: &str) -> Vec<(String, String)> {
    let mut documents: Vec<(String, String)> = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("{directory} holds the case documents: {error}"))
        .map(|entry| entry.expect("a directory entry is readable").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "md"))
        .map(|path| {
            let stem = path
                .file_stem()
                .expect("a file has a name")
                .to_string_lossy()
                .to_string();

            // `nucleoid.spec.synth.01` is numbered by its last segment.
            let number = stem.rsplit('.').next().unwrap_or(&stem).to_string();

            (
                format!("{directory}_{number}"),
                path.to_string_lossy().replace('\\', "/"),
            )
        })
        .collect();

    documents.sort();
    documents
}

/// Writes the list of discovered documents, so the test files can hold them
/// without naming each one. `include_str!` needs a literal path, which is why
/// this is generated rather than globbed at test time.
fn write_document_list(out: &str, documents: &[(String, String)]) {
    let root = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let root = root.replace('\\', "/");

    let mut generated = String::from("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("pub static SYNTH_DOCUMENTS: &[(&str, &str, &str)] = &[\n");

    for (module, path) in documents {
        writeln!(
            generated,
            "    ({module:?}, {path:?}, include_str!(\"{root}/{path}\")),"
        )
        .unwrap();
    }

    generated.push_str("];\n");

    fs::write(Path::new(out).join("synth_documents.rs"), generated)
        .expect("the generated document list must be writable");
}

/// The title of every case in a case document, in order.
///
/// Deliberately the same rule as `cases()` in `tests/common/mod.rs`: split the
/// fenced block on `---`, and take each case's first comment line as its title.
/// The two are checked against each other at test time — a generated test looks
/// its case up by title and fails loudly if it is not there, and the count above
/// is compared with the count the harness parses.
fn case_titles(document: &str) -> Vec<String> {
    let document = document.replace("\r\n", "\n");

    let body = document
        .split("```")
        .nth(1)
        .expect("cases live in one fenced block");

    body.split("\n---\n")
        .filter(|block| !block.trim().is_empty())
        .map(|block| {
            block
                .lines()
                .map(str::trim)
                .find(|line| line.starts_with('#'))
                .unwrap_or("untitled")
                .trim_start_matches('#')
                .trim()
                .to_string()
        })
        .collect()
}

/// The title of every fenced `nuc` snippet in a prose document.
///
/// A snippet is titled by the claim it is there to demonstrate — the last bold
/// line before it. The same rule as `snippets()` in `tests/readme.rs`.
fn snippet_titles(document: &str) -> Vec<String> {
    let document = document.replace("\r\n", "\n");

    let mut titles = Vec::new();
    let mut claim = String::new();

    for line in document.lines() {
        let line = line.trim();

        if line.len() > 4 && line.starts_with("**") && line.ends_with("**") {
            claim = line
                .trim_matches('*')
                .trim()
                .trim_end_matches('.')
                .to_string();
        }

        if line.starts_with("```nuc") {
            titles.push(if claim.is_empty() {
                format!("snippet {}", titles.len() + 1)
            } else {
                claim.clone()
            });
        }
    }

    titles
}

fn module_for(module: &str, document: usize, titles: &[String]) -> String {
    let mut out = String::new();

    writeln!(out, "mod {module} {{").unwrap();

    let mut taken: Vec<String> = Vec::new();

    for title in titles {
        let name = unique(identifier(title), &mut taken);

        writeln!(out, "    /// {title}").unwrap();
        writeln!(out, "    #[test]").unwrap();
        writeln!(out, "    fn {name}() {{").unwrap();
        writeln!(out, "        crate::case({document}, {title:?});").unwrap();
        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");
    out
}

/// A Rust function name for a case title. `Nucleoid runs a statement in the
/// state` becomes `runs_a_statement_in_the_state`, so the module path reads the
/// way the sentence does.
fn identifier(title: &str) -> String {
    let title = title.strip_prefix("Nucleoid ").unwrap_or(title);

    let mut name = String::new();
    let mut separated = true;

    for character in title.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
            separated = false;
        } else if !separated {
            name.push('_');
            separated = true;
        }
    }

    while name.ends_with('_') {
        name.pop();
    }

    if name.is_empty() {
        name.push_str("case");
    }

    // A name that starts with a digit, or that is a keyword, is not an
    // identifier.
    if name.starts_with(|character: char| character.is_ascii_digit()) || is_keyword(&name) {
        name.insert_str(0, "case_");
    }

    name
}

/// Refuses a document in which two cases carry the same title.
///
/// The generated tests find their case by title, so a repeated title would
/// leave the second case unreachable — its test would run the first one over
/// again, and the count would still add up. Renaming the collision away in the
/// generated identifiers, as [`unique`] does, would hide exactly that. Distinct
/// titles that happen to *normalise* to the same identifier are fine, since
/// each still looks up its own case.
fn reject_duplicates(path: &str, titles: &[String]) {
    for (index, title) in titles.iter().enumerate() {
        if titles[..index].contains(title) {
            panic!(
                "{path} has two cases titled {title:?}; \
                 the second could never be run, because a case is found by its title"
            );
        }
    }
}

/// Two titles may normalise to the same identifier; the names still have to
/// differ.
fn unique(name: String, taken: &mut Vec<String>) -> String {
    if !taken.contains(&name) {
        taken.push(name.clone());
        return name;
    }

    for suffix in 2.. {
        let candidate = format!("{name}_{suffix}");

        if !taken.contains(&candidate) {
            taken.push(candidate.clone());
            return candidate;
        }
    }

    unreachable!("the search for a free name does not end")
}

fn is_keyword(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "try",
        "type", "union", "unsafe", "use", "where", "while", "yield",
    ];

    KEYWORDS.contains(&name)
}
