//! Turns the language's executable documents and exported JSONL into named
//! Rust tests.
//!
//! `ref/src/test/nucleoid.spec.js` writes one `it(...)` per behaviour, so a
//! failure names the behaviour that broke. The cases here live in the documents
//! rather than in the test files, so the `it`s are generated from them — which
//! also keeps the promise in `CLAUDE.md` that adding a case to a document adds
//! a test, with nothing else to edit.
//!
//! Spec and synth records are exported as self-contained tests: each generated
//! function embeds the code and expected return it runs. This gives readable
//! BDD-style behavior names without Gherkin or runtime document parsing.

use serde::Deserialize;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// How a document holds its cases.
#[derive(Clone, Copy, PartialEq)]
enum Format {
    /// A fenced block of cases split by `---`, each titled by its first comment
    /// line.
    Cases,
    /// Prose with fenced `nuc` blocks in it, each titled by the bold claim
    /// it demonstrates.
    Snippets,
}

/// One generated test file, and the documents whose cases go into it. Each
/// document becomes a module, the way `describe(...)` groups `it`s.
struct Suite {
    output: &'static str,
    format: Format,
    documents: &'static [(&'static str, &'static str)],
}

const SUITES: &[Suite] = &[
    Suite {
        output: "reference.rs",
        format: Format::Cases,
        documents: &[("reference", "tests/reference.md")],
    },
    Suite {
        output: "readme.rs",
        format: Format::Snippets,
        documents: &[("readme", "README.md")],
    },
    Suite {
        output: "examples.rs",
        format: Format::Snippets,
        documents: &[("examples", "docs/examples.md")],
    },
];

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-env-changed=UPDATE_SPEC_TESTS");

    let out = env::var("OUT_DIR").expect("cargo sets OUT_DIR for build scripts");
    let synth_documents = in_directory("synth");
    write_document_list(&out, &synth_documents);
    write_json_tests(&out);

    for suite in SUITES {
        let mut generated = String::new();
        generated.push_str("// @generated by build.rs — do not edit.\n\n");

        let mut total = 0;
        let mut modules = String::new();

        let documents: Vec<(String, String)> = suite
            .documents
            .iter()
            .map(|(module, path)| ((*module).to_string(), (*path).to_string()))
            .collect();

        for (index, (module, path)) in documents.iter().enumerate() {
            println!("cargo::rerun-if-changed={path}");

            let document = fs::read_to_string(path)
                .unwrap_or_else(|error| panic!("{path} states what the language does: {error}"));

            let titles = match suite.format {
                Format::Cases => case_titles(&document),
                Format::Snippets => snippet_titles(&document),
            };

            reject_duplicates(path, &titles);

            total += titles.len();
            modules.push_str(&module_for(module, index, &titles));
        }

        writeln!(generated, "pub const GENERATED: usize = {total};\n").unwrap();
        generated.push_str(&modules);

        fs::write(Path::new(&out).join(suite.output), generated)
            .expect("the generated tests must be writable");
    }
}

#[derive(Deserialize)]
struct Record {
    description: String,
    code: String,
    #[serde(rename = "return")]
    returns: Option<String>,
}

/// Exports every JSONL record as one named Rust test with its data embedded.
fn write_json_tests(out: &str) {
    println!("cargo::rerun-if-changed=dataset");
    let spec = render_json_tests("dataset/spec.jsonl", None);

    fs::write(Path::new(out).join("spec_cases.rs"), &spec)
        .expect("the generated spec tests must be writable");

    if env::var_os("UPDATE_SPEC_TESTS").is_some() {
        fs::create_dir_all("tests/spec_cases").expect("tests/spec_cases must be writable");
        fs::write("tests/spec_cases/mod.rs", spec)
            .expect("tests/spec_cases/mod.rs must be writable");
    }

    let mut paths: Vec<String> = fs::read_dir("dataset")
        .expect("dataset holds exported tests")
        .map(|entry| entry.expect("a dataset entry is readable").path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.starts_with("synth.") && name.ends_with(".jsonl"))
        })
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect();
    paths.sort();

    let mut synth = String::from("// @generated from dataset JSONL by build.rs — do not edit.\n\n");
    let mut total = 0;

    for path in paths {
        let number = Path::new(&path)
            .file_stem()
            .and_then(|stem| stem.to_str())
            .and_then(|stem| stem.rsplit('.').next())
            .expect("a synth dataset has a number");
        let records = records(&path);

        total += records.len();
        synth.push_str(&render_records(&records, Some(&format!("synth_{number}"))));
    }

    writeln!(synth, "pub const GENERATED: usize = {total};").unwrap();
    fs::write(Path::new(out).join("synth.rs"), synth)
        .expect("the generated synth tests must be writable");
}

fn render_json_tests(path: &str, module: Option<&str>) -> String {
    let mut generated =
        String::from("// @generated from dataset JSONL by build.rs — do not edit.\n\n");
    generated.push_str(&render_records(&records(path), module));
    generated
}

fn records(path: &str) -> Vec<Record> {
    println!("cargo::rerun-if-changed={path}");
    fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("{path} holds exported tests: {error}"))
        .lines()
        .enumerate()
        .filter(|(_, line)| !line.trim().is_empty())
        .map(|(index, line)| {
            serde_json::from_str(line)
                .unwrap_or_else(|error| panic!("{path}:{}: {error}", index + 1))
        })
        .collect()
}

fn render_records(records: &[Record], module: Option<&str>) -> String {
    let mut generated = String::new();
    let mut taken = Vec::new();

    if let Some(module) = module {
        writeln!(generated, "mod {module} {{").unwrap();
        writeln!(generated, "    use crate::common::runner;\n").unwrap();
    }

    let indent = if module.is_some() { "    " } else { "" };

    for record in records {
        let name = unique(identifier(&record.description), &mut taken);

        writeln!(generated, "{indent}/// {}", record.description).unwrap();
        writeln!(generated, "{indent}#[test]").unwrap();
        writeln!(generated, "{indent}fn {name}() {{").unwrap();
        writeln!(generated, "{indent}    let mut run = runner();").unwrap();

        let mut statements: Vec<String> = statements(&record.code)
            .into_iter()
            .map(|statement| without_comments(&statement))
            .collect();

        if let Some(expected) = &record.returns {
            let last = statements
                .iter_mut()
                .rfind(|statement| !is_assertion(statement))
                .expect("a return expectation belongs to a statement");
            write!(last, "\n\n# return: {expected}").unwrap();
        }

        let mut nested_assertion = 0;

        for statement in statements {
            if let Some((actual, expected)) = assertion(&statement) {
                if let Some(expected) = rust_expected(expected) {
                    writeln!(
                        generated,
                        "{indent}    assert_eq!(run({}), {expected});",
                        rust_literal(actual)
                    )
                    .unwrap();
                } else {
                    writeln!(generated, "{indent}    {{").unwrap();
                    writeln!(
                        generated,
                        "{indent}        let actual = run({});",
                        rust_literal(actual)
                    )
                    .unwrap();
                    writeln!(
                        generated,
                        "{indent}        let expected = run({});",
                        rust_literal(&format!("({expected})"))
                    )
                    .unwrap();
                    writeln!(generated, "{indent}        assert_eq!(actual, expected);").unwrap();
                    writeln!(generated, "{indent}    }}").unwrap();
                }
            } else {
                let (statement, assertions) =
                    lift_nested_assertions(&statement, &mut nested_assertion);

                for assertion in &assertions {
                    writeln!(
                        generated,
                        "{indent}    run({:?});",
                        format!("{}_actual = null", assertion)
                    )
                    .unwrap();
                    writeln!(
                        generated,
                        "{indent}    run({:?});",
                        format!("{}_expected = null", assertion)
                    )
                    .unwrap();
                    writeln!(
                        generated,
                        "{indent}    run({:?});",
                        format!("{}_ran = false", assertion)
                    )
                    .unwrap();
                }

                writeln!(generated, "{indent}    run({});", rust_literal(&statement)).unwrap();

                for assertion in assertions {
                    writeln!(
                        generated,
                        "{indent}    assert_eq!(run({:?}), true);",
                        format!("{assertion}_ran")
                    )
                    .unwrap();
                    writeln!(generated, "{indent}    {{").unwrap();
                    writeln!(
                        generated,
                        "{indent}        let actual = run({:?});",
                        format!("{assertion}_actual")
                    )
                    .unwrap();
                    writeln!(
                        generated,
                        "{indent}        let expected = run({:?});",
                        format!("({assertion}_expected)")
                    )
                    .unwrap();
                    writeln!(generated, "{indent}        assert_eq!(actual, expected);").unwrap();
                    writeln!(generated, "{indent}    }}").unwrap();
                }
            }
        }

        writeln!(generated, "{indent}}}\n").unwrap();
    }

    if module.is_some() {
        generated.push_str("}\n\n");
    }

    generated
}

/// Splits a case into top-level statements while retaining comments and blocks.
fn statements(source: &str) -> Vec<String> {
    let source = source.replace("\r\n", "\n");
    let mut statements = Vec::new();
    let mut current: Vec<&str> = Vec::new();
    let mut pending: Vec<&str> = Vec::new();

    for line in source.lines() {
        let trimmed = line.trim();
        let top_level = line.len() == line.trim_start().len();
        let comment_or_blank = trimmed.is_empty() || trimmed.starts_with('#');
        let continuation = trimmed.starts_with("else:")
            || trimmed.starts_with("else if ")
            || trimmed.starts_with("elif ")
            || trimmed.starts_with("catch ")
            || trimmed.starts_with("finally:")
            || trimmed.starts_with([')', ']', '}']);

        if comment_or_blank {
            pending.push(line);
        } else if top_level && !continuation {
            if !current.is_empty() {
                statements.push(current.join("\n").trim().to_string());
                current.clear();
            }

            current.append(&mut pending);
            current.push(line);
        } else {
            current.append(&mut pending);
            current.push(line);
        }
    }

    if !current.is_empty() {
        statements.push(current.join("\n").trim().to_string());
    }

    assert!(!statements.is_empty(), "a dataset record has no statements");
    statements
}

fn is_assertion(statement: &str) -> bool {
    assertion(statement).is_some()
}

fn assertion(statement: &str) -> Option<(&str, &str)> {
    let statement = statement.trim();
    let arguments = statement.strip_prefix("assert(")?.strip_suffix(')')?;
    let mut depth = 0;
    let mut quote = None;
    let mut escaped = false;

    for (index, character) in arguments.char_indices() {
        if let Some(delimiter) = quote {
            if escaped {
                escaped = false;
            } else if character == '\\' {
                escaped = true;
            } else if character == delimiter {
                quote = None;
            }

            continue;
        }

        match character {
            '"' | '\'' | '`' => quote = Some(character),
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => depth -= 1,
            ',' if depth == 0 => {
                let actual = arguments[..index].trim();
                let expected = arguments[index + character.len_utf8()..].trim();
                return Some((actual, expected));
            }
            _ => {}
        }
    }

    None
}

fn lift_nested_assertions(statement: &str, index: &mut usize) -> (String, Vec<String>) {
    let mut generated = Vec::new();
    let mut assertions = Vec::new();

    for line in statement.lines() {
        let trimmed = line.trim();

        if let Some((actual, expected)) = assertion(trimmed) {
            let indentation = &line[..line.len() - line.trim_start().len()];
            let name = format!("__nucleoid_test_assertion_{}", *index);
            *index += 1;

            generated.push(format!("{indentation}{name}_actual = {actual}"));
            generated.push(format!("{indentation}{name}_expected = {expected}"));
            generated.push(format!("{indentation}{name}_ran = true"));
            assertions.push(name);
        } else {
            generated.push(line.to_string());
        }
    }

    (generated.join("\n"), assertions)
}

fn rust_expected(expected: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(expected).ok()?;

    Some(match value {
        serde_json::Value::Null => "serde_json::Value::Null".to_string(),
        serde_json::Value::Bool(value) => value.to_string(),
        serde_json::Value::Number(value) => match value.as_i64() {
            Some(number) if i32::try_from(number).is_err() => format!("{expected}.0"),
            _ => expected.to_string(),
        },
        serde_json::Value::String(value) => format!("{value:?}"),
        serde_json::Value::Array(_) | serde_json::Value::Object(_) => {
            format!("serde_json::json!({expected})")
        }
    })
}

fn without_comments(statement: &str) -> String {
    statement
        .lines()
        .filter(|line| !line.trim().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

fn rust_literal(value: &str) -> String {
    if !value.contains(['\n', '\r', '"', '\\']) {
        return format!("{value:?}");
    }

    for hashes in 1.. {
        let marker = format!("\"{}", "#".repeat(hashes));

        if !value.contains(&marker) {
            let hashes = "#".repeat(hashes);
            return format!("r{hashes}\"{value}\"{hashes}");
        }
    }

    unreachable!("a raw string delimiter is always available")
}

/// Every `.md` in a directory, as `(module, path)` in name order.
///
/// `synth/nucleoid.spec.synth.01.md` becomes the module `synth_01`, so a test
/// path still says which set the case came from.
fn in_directory(directory: &str) -> Vec<(String, String)> {
    let mut documents: Vec<(String, String)> = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("{directory} holds the case documents: {error}"))
        .map(|entry| entry.expect("a directory entry is readable").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "md"))
        .map(|path| {
            let stem = path
                .file_stem()
                .expect("a file has a name")
                .to_string_lossy()
                .to_string();

            // `nucleoid.spec.synth.01` is numbered by its last segment.
            let number = stem.rsplit('.').next().unwrap_or(&stem).to_string();

            (
                format!("{directory}_{number}"),
                path.to_string_lossy().replace('\\', "/"),
            )
        })
        .collect();

    documents.sort();
    documents
}

/// Writes the list of discovered documents, so the test files can hold them
/// without naming each one. `include_str!` needs a literal path, which is why
/// this is generated rather than globbed at test time.
fn write_document_list(out: &str, documents: &[(String, String)]) {
    let root = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let root = root.replace('\\', "/");

    let mut generated = String::from("// @generated by build.rs — do not edit.\n\n");
    generated.push_str("pub static SYNTH_DOCUMENTS: &[(&str, &str, &str)] = &[\n");

    for (module, path) in documents {
        writeln!(
            generated,
            "    ({module:?}, {path:?}, include_str!(\"{root}/{path}\")),"
        )
        .unwrap();
    }

    generated.push_str("];\n");

    fs::write(Path::new(out).join("synth_documents.rs"), generated)
        .expect("the generated document list must be writable");
}

/// The title of every case in a case document, in order.
///
/// Deliberately the same rule as `cases()` in `tests/common/mod.rs`: split the
/// fenced block on `---`, and take each case's first comment line as its title.
/// The two are checked against each other at test time — a generated test looks
/// its case up by title and fails loudly if it is not there, and the count above
/// is compared with the count the harness parses.
fn case_titles(document: &str) -> Vec<String> {
    let document = document.replace("\r\n", "\n");

    let body = document
        .split("```")
        .nth(1)
        .expect("cases live in one fenced block");

    body.split("\n---\n")
        .filter(|block| !block.trim().is_empty())
        .map(|block| {
            block
                .lines()
                .map(str::trim)
                .find(|line| line.starts_with('#'))
                .unwrap_or("untitled")
                .trim_start_matches('#')
                .trim()
                .to_string()
        })
        .collect()
}

/// The title of every fenced `nuc` snippet in a prose document.
///
/// A snippet is titled by the claim it is there to demonstrate — the last bold
/// line before it. The same rule as `snippets()` in `tests/readme.rs`.
fn snippet_titles(document: &str) -> Vec<String> {
    let document = document.replace("\r\n", "\n");

    let mut titles = Vec::new();
    let mut claim = String::new();

    for line in document.lines() {
        let line = line.trim();

        if line.len() > 4 && line.starts_with("**") && line.ends_with("**") {
            claim = line
                .trim_matches('*')
                .trim()
                .trim_end_matches('.')
                .to_string();
        }

        if line.starts_with("```nuc") {
            titles.push(if claim.is_empty() {
                format!("snippet {}", titles.len() + 1)
            } else {
                claim.clone()
            });
        }
    }

    titles
}

fn module_for(module: &str, document: usize, titles: &[String]) -> String {
    let mut out = String::new();

    writeln!(out, "mod {module} {{").unwrap();

    let mut taken: Vec<String> = Vec::new();

    for title in titles {
        let name = unique(identifier(title), &mut taken);

        writeln!(out, "    /// {title}").unwrap();
        writeln!(out, "    #[test]").unwrap();
        writeln!(out, "    fn {name}() {{").unwrap();
        writeln!(out, "        crate::case({document}, {title:?});").unwrap();
        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");
    out
}

/// A Rust function name for a case title. `Nucleoid runs a statement in the
/// state` becomes `runs_a_statement_in_the_state`, so the module path reads the
/// way the sentence does.
fn identifier(title: &str) -> String {
    let title = title.strip_prefix("Nucleoid ").unwrap_or(title);

    let mut name = String::new();
    let mut separated = true;

    for character in title.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
            separated = false;
        } else if !separated {
            name.push('_');
            separated = true;
        }
    }

    while name.ends_with('_') {
        name.pop();
    }

    if name.is_empty() {
        name.push_str("case");
    }

    // A name that starts with a digit, or that is a keyword, is not an
    // identifier.
    if name.starts_with(|character: char| character.is_ascii_digit()) || is_keyword(&name) {
        name.insert_str(0, "case_");
    }

    name
}

/// Refuses a document in which two cases carry the same title.
///
/// The generated tests find their case by title, so a repeated title would
/// leave the second case unreachable — its test would run the first one over
/// again, and the count would still add up. Renaming the collision away in the
/// generated identifiers, as [`unique`] does, would hide exactly that. Distinct
/// titles that happen to *normalise* to the same identifier are fine, since
/// each still looks up its own case.
fn reject_duplicates(path: &str, titles: &[String]) {
    for (index, title) in titles.iter().enumerate() {
        if titles[..index].contains(title) {
            panic!(
                "{path} has two cases titled {title:?}; \
                 the second could never be run, because a case is found by its title"
            );
        }
    }
}

/// Two titles may normalise to the same identifier; the names still have to
/// differ.
fn unique(name: String, taken: &mut Vec<String>) -> String {
    if !taken.contains(&name) {
        taken.push(name.clone());
        return name;
    }

    for suffix in 2.. {
        let candidate = format!("{name}_{suffix}");

        if !taken.contains(&candidate) {
            taken.push(candidate.clone());
            return candidate;
        }
    }

    unreachable!("the search for a free name does not end")
}

fn is_keyword(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "try",
        "type", "union", "unsafe", "use", "where", "while", "yield",
    ];

    KEYWORDS.contains(&name)
}
