//! The worked examples in `docs/examples.md`, run as one test per example.
//!
//! The page promises that every example is a complete program that runs as
//! written, so it is executed from the file itself rather than copied here.
//! Each example is named after the claim it demonstrates, so a failure says
//! which example the language no longer matches.
//!
//! The tests are generated by `build.rs` — see there for why.

mod common;

use std::sync::LazyLock;

const EXAMPLES: &str = include_str!("../docs/examples.md");
const REFERENCE: &str = include_str!("../docs/reference.md");

/// Sections of the reference that no example answers to. A table of syntax
/// forms is not a program, so there is nothing to run for it.
const WITHOUT_EXAMPLES: &[&str] = &["Syntax Summary"];

static DOCUMENTS: LazyLock<Vec<Vec<common::Case>>> =
    LazyLock::new(|| vec![common::snippets(EXAMPLES, "docs/examples.md")]);

include!(concat!(env!("OUT_DIR"), "/examples.rs"));

/// Runs the example with this title. Called by each generated test.
fn case(document: usize, title: &str) {
    common::run_case(&DOCUMENTS, document, title);
}

/// Every example on the page has a test of its own, and there is at least one.
#[test]
fn every_example_is_covered() {
    let total = common::total(&DOCUMENTS);

    assert!(total > 0, "docs/examples.md shows no Nucleoid");

    assert_eq!(
        total, GENERATED,
        "build.rs generated {GENERATED} tests for the examples in docs/examples.md"
    );
}

/// The examples page is the reference worked as programs, so it carries the
/// same sections under the same names and in the same order. A section added to
/// one document and not the other fails here rather than going unnoticed.
#[test]
fn the_sections_follow_the_reference() {
    let documented: Vec<String> = sections(REFERENCE)
        .into_iter()
        .filter(|section| !WITHOUT_EXAMPLES.contains(&section.as_str()))
        .collect();

    // Two empty lists would agree with each other and prove nothing.
    assert!(
        !documented.is_empty(),
        "no numbered sections found in docs/reference.md"
    );

    assert_eq!(
        sections(EXAMPLES),
        documented,
        "docs/examples.md must follow the sections of docs/reference.md"
    );
}

/// The numbered `## N. Name` headings of a document, in order.
fn sections(document: &str) -> Vec<String> {
    document
        .lines()
        .filter_map(|line| line.trim().strip_prefix("## "))
        .filter_map(|heading| heading.split_once(". "))
        .filter(|(number, _)| number.chars().all(|character| character.is_ascii_digit()))
        .map(|(_, name)| name.trim().to_string())
        .collect()
}
