//! The Nucleoid snippets in `README.md`, run as one test per claim.
//!
//! They are the first thing anyone reads, so they are executed from the file
//! itself rather than copied here — there is nothing to drift. Each snippet is
//! named after the claim it demonstrates, so a failure says which promise the
//! README is no longer keeping.
//!
//! The tests are generated by `build.rs` — see there for why.

mod common;

use std::sync::LazyLock;

const README: &str = include_str!("../README.md");

static DOCUMENTS: LazyLock<Vec<Vec<common::Case>>> =
    LazyLock::new(|| vec![common::snippets(README, "README.md")]);

include!(concat!(env!("OUT_DIR"), "/readme.rs"));

/// Runs the snippet with this title. Called by each generated test.
fn case(document: usize, title: &str) {
    common::run_case(&DOCUMENTS, document, title);
}

/// Every snippet in the README has a test of its own, and there is at least one
/// — the README should show what the language looks like.
#[test]
fn every_snippet_is_covered() {
    let total = common::total(&DOCUMENTS);

    assert!(total > 0, "README.md shows no Nucleoid");

    assert_eq!(
        total, GENERATED,
        "build.rs generated {GENERATED} tests for the snippets in README.md"
    );
}
