//! The behaviours stated in `docs/reference.md`, kept executable here and run
//! as one test per behaviour.
//!
//! The tests are generated by `build.rs` — see there for why.

mod common;

use std::sync::LazyLock;

static DOCUMENTS: LazyLock<Vec<Vec<common::Case>>> =
    LazyLock::new(|| vec![common::cases(include_str!("reference.md"))]);

include!(concat!(env!("OUT_DIR"), "/reference.rs"));

/// Runs the case with this title. Called by each generated test.
fn case(document: usize, title: &str) {
    common::run_case(&DOCUMENTS, document, title);
}

/// Every case in the document has a test of its own.
#[test]
fn every_case_is_covered() {
    assert_eq!(
        common::total(&DOCUMENTS),
        GENERATED,
        "build.rs generated {GENERATED} tests for the cases in tests/reference.md"
    );
}
