//! The synthesized use cases, which are derived from `nucleoid.spec.md`, run as
//! one test per behaviour.
//!
//! Each document is its own module, so a failure says which synth set it came
//! from. The tests are generated by `build.rs` — see there for why.

mod common;

use std::sync::LazyLock;

static DOCUMENTS: LazyLock<Vec<Vec<common::Case>>> = LazyLock::new(|| {
    vec![
        common::cases(include_str!("../synth/nucleoid.spec.synth.01.md")),
        common::cases(include_str!("../synth/nucleoid.spec.synth.02.md")),
    ]
});

include!(concat!(env!("OUT_DIR"), "/synth.rs"));

/// Runs the case with this title. Called by each generated test.
fn case(document: usize, title: &str) {
    common::run_case(&DOCUMENTS, document, title);
}

/// Every case in every synth document has a test of its own.
#[test]
fn every_case_is_covered() {
    assert_eq!(
        common::total(&DOCUMENTS),
        GENERATED,
        "build.rs generated {GENERATED} tests for the cases in synth/"
    );
}
