#!/bin/sh
set -e

message=`cat $1`
list=`echo $message | aspell list`

if [ -n "$list" ]; then
  echo "Misspelled Word(s):"
  echo "$list"
  read -p "Still continue? (Y): " input < /dev/tty

    if [ "$input" != "Y" ]; then
      exit 1
    fi
fi

(echo "$message" | grep -Pq "^\S((?!.*  ).*\S)?$") || (echo "There are multiple spaces in commit message." ; exit 2)
