#!/usr/bin/env node
const execSync = require("child_process").execSync;

function run(n, c) {
  let code = execSync(
    `mocha ./test/performance.spec.js -n=${n} -c=${c} --reporter=JSON`
  );

  return JSON.parse(code.toString()).tests;
}

var ns = [10, 100];
var cs = [0, 1];
var charts = [];

for (let c of cs) {
  let traces = [];

  for (let i = 0; i < 5; i++) {
    traces[i] = {
      x: [],
      y: [],
      type: "scatter"
    };
  }

  for (let n of ns) {
    let tests = run(n, c);

    for (let t = 0; t < 5; t++) {
      let test = tests[t];
      traces[t].x.push(test.duration);
      traces[t].y.push(n);
      traces[t].name = `Test #${t + 1}`;
    }
  }

  charts.push({
    traces,
    c
  });
}

console.log(JSON.stringify(charts));
